### ISSUE TITLE
Standardize Working groups repositoryoy structure

### ISSUE THREAD

**Issue by friyaz** [chaoss/wg-app-ecosystem#10]
Hello everyone,

We are trying to make a standard and uniform repository structure for all working groups of CHAOSS. This will make things easier for new members. See this [document](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#) to know details about the proposed repo structure.

Please provide your feedback or concern about this proposal.

**Comment by GeorgLink** [comment]
Thanks @friyaz 

The App Ecosystem WG doesn't currently define metrics and doesn't have a repo structure need to be aligned with the other working groups. We can ignore this WG for the standard repo structure
